- format: h3
  height: 1
  type: text
  value: {{Title}}
- body:
  - - metrics:
      - - AWS/ApiGateway
        - Count
        - ApiName
        - {{ResourceName}}
        - period: 300
          stat: Sum
      region: ${AWS::Region}
      stacked: false
      title: "Count: Sum"
      view: timeSeries
    - metrics:
      - - AWS/ApiGateway
        - 5XXError
        - ApiName
        - {{ResourceName}}
        - period: 300
          stat: Sum
      region: ${AWS::Region}
      stacked: false
      title: "5XXError: Sum"
      view: timeSeries
    - metrics:
      - - AWS/ApiGateway
        - 4XXError
        - ApiName
        - {{ResourceName}}
        - period: 300
          stat: Sum
      region: ${AWS::Region}
      stacked: false
      title: "4XXError: Sum"
      view: timeSeries
  - - metrics:
      - - AWS/ApiGateway
        - Latency
        - ApiName
        - {{ResourceName}}
        - period: 300
          stat: Average
      region: ${AWS::Region}
      stacked: false
      title: "Latency: Average"
      view: timeSeries
    - metrics:
      - - AWS/ApiGateway
        - IntegrationLatency
        - ApiName
        - {{ResourceName}}
        - period: 300
          stat: Average
      region: ${AWS::Region}
      stacked: false
      title: "Integration Latency: Average"
      view: timeSeries
  height: 6
  type: charts