- format: h3
  height: 1
  type: text
  value: {{Title}}
- body:
  - - metrics:
      - - AWS/Events
        - TriggeredRules
        - RuleName
        - {{ResourceName}}
      region: ${AWS::Region}
      stacked: false
      title: TriggeredRules
      view: timeSeries
    - metrics:
      - - AWS/Events
        - Invocations
        - RuleName
        - {{ResourceName}}
      region: ${AWS::Region}
      stacked: false
      stat: Average
      title: Invocations
      view: timeSeries
    - metrics:
      - - AWS/Events
        - FailedInvocations
        - RuleName
        - {{ResourceName}}
      region: ${AWS::Region}
      stacked: false
      stat: Average
      title: FailedInvocations
      view: timeSeries
  height: 6
  type: charts
