- format: h3
  height: 1
  type: text
  value: {{Title}}
- body:
  - - metrics:
      - - AWS/S3
        - BucketSizeBytes
        - BucketName
        - {{ResourceName}}
        - StorageType
        - StandardStorage
        - period: 86400
          stat: Average
      region: ${AWS::Region}
      stacked: false
      title: 'BucketSizeBytes: Average'
      view: timeSeries
    - metrics:
      - - AWS/S3
        - NumberOfObjects
        - BucketName
        - {{ResourceName}}
        - StorageType
        - AllStorageTypes
        - period: 86400
          stat: Average
      region: ${AWS::Region}
      stacked: false
      title: 'NumberOfObjects: Average'
      view: timeSeries
  height: 6
  type: charts
