actions:
- endpoint:
    path: hello-get
    method: GET
    parameters:
    - message
  name: demo-hello-get
  size: small
  timeout: short
- endpoint:
    path: hello-post
    method: POST
    schema:
      type: object
      properties:
        message:
          type: string
      required:
        - message
  name: demo-hello-post
  size: small
  timeout: short
- name: demo-streaming-bucket
  size: small
  timeout: short
- name: demo-streaming-table
  permissions:
  - dynamodb
  size: small
  timeout: short
api:
  name: api
  authorized: false
  stage:
    name: 1-0-0
bucket:
  name: demo-streaming-bucket
dashboard:
  name: dashboard
errors:
  name: demo-errors
  size: small
  timeout: short
events:
  name: events
secrets: []
table:
  indexes: []
  name: demo-streaming-table
  stream:
    retries: 3
    batch:
      window: 1
    type: NEW_AND_OLD_IMAGES    
users:
  name: users